version: '3.9'

services:
  postgres:
    container_name: basic-postgres
    image: postgres
    env_file: postgres.env
    environment:
      PGDATA: /data/postgres
    expose:
      - 5432

  web:
    container_name: web-container
    build: ./
    env_file:
      - db.env
    depends_on:
      - elasticsearch
    ports:
      - 8000:8000

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    depends_on:
      - postgres
    ports:
    - 9300:9300
    - 9200:9200
